### ISSUE TITLE
Token invalid

### ISSUE THREAD

**Issue by luukgruijs** [colymba/silverstripe-restfulapi#28]
Hi,

I can't get the authentication to work. It's keep saying "Token invalid" when i type in 'api/Model/id'. What am i missing?

Here's my config file:

```
SSViewer:
  theme: 'simple'
# API access
TherapyGroup:
  api_access: true
Patient:
  api_access: true
Therapist:
  api_access: true
Exercise:
  api_access: true
Message:
  api_access: true
# RestfulAPI config
RESTfulAPI:
  authentication_policy: true
  access_control_policy: 'ACL_CHECK_CONFIG_ONLY'
  dependencies:
    authenticator: '%$RESTfulAPI_TokenAuthenticator'
  cors:
    Enabled: true
    Allow-Origin: '*'
    Allow-Headers: '*'
    Allow-Methods: 'OPTIONS, GET, POST, PUT'
    Max-Age: 86400
  embedded_records:
    Patient:
      - 'Exercises'
      - 'Therapist'
      - 'TherapyGroup'
      - 'Messages'
    Exercise:
      - 'Messages'
  RESTfulAPI_TokenAuthenticator:
    tokenOwnerClass: 'Member'
Member:
  extensions:
    - RESTfulAPI_TokenAuthExtension
```

Do you know the solution? Thanks in advance.
