### ISSUE TITLE
Access token authenticated Member::currentUser() in onAfterDeserialize function

### ISSUE THREAD

**Issue by jonshutt** [colymba/silverstripe-restfulapi#72]
I'm wondering it's possible to access Member::currentUser() data within the onAfterDeserialize function on my model.

I'm logging in and authenticating ok using the API and passing the token back which I can read in the canCreate() function.

Idea is that if a user creates an entry, it will put their ID against it in the onAfterDeserialize rather than posting up their ID

**Comment by colymba** [comment]
If you are using the TokenAuth and the token is stored on a Member dataobject, when the Authenticator validates the token the Member gets login at the same time.

So theoretically, `Member::currentUser()` should work anywhere. Have you tried it?

**Comment by jonshutt** [comment]
I think my problem my be that the member is authenticated when I log in and get their details, but i haven't set up the 'log' dataobject / endpoint to use the authenticated user... 

```
Log:
  api_access: 'GET,POST'
   
Member:
  api_access: 'GET'
  extensions:
    - RESTfulAPI_TokenAuthExtension
```

**Comment by colymba** [comment]
That config snippet seems fine. What's the config for `RestfulAPI`?

**Comment by jonshutt** [comment]
config is 

``` 
Log:
  api_access: 'GET,POST'
   
Member:
  extensions:
    - RESTfulAPI_TokenAuthExtension

# RestfulAPI config
RESTfulAPI:
  #authentication_policy: true
  access_control_policy: 'ACL_CHECK_CONFIG_AND_MODEL'
  dependencies:
    authenticator: '%$RESTfulAPI_TokenAuthenticator'
  cors:
    Enabled: true
    Allow-Origin: '*'
    Allow-Headers: '*'
    Allow-Methods: 'GET,POST'
    Max-Age: 86400
  RESTfulAPI_TokenAuthenticator:
    tokenOwnerClass: 'Member'
```


in my 'log' data object I have 

`
public function onAfterDeserialize(&$data) {
   print_r($data);
   print_r(Member::currentUser());
   print_r(Member::currentUser()->ID);
}
`
which is displaying the data posted, but not the member info.

if i add a 'canCreate' function eg:

`
function canCreate($member = null) { 
if(!$member) $member = Member::currentUser();
print "create:";
print $member->ID;
return true;
}`

then within there I can see the member  info in there
